Human Activity Recognition
========================================================
##Backgroud
See the link http://groupware.les.inf.puc-rio.br/har

```{r}
# enable multi-core processing to save time
#library(doParallel)
#cl <- makeCluster(detectCores())
#registerDoParallel(cl)
```

##Data Access
```{r,cache=TRUE}
url1<-'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv'
url2<-'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv'
download.file(url1,destfile = 'training.csv',method = 'curl')
download.file(url2,destfile = 'test.csv',method = 'curl')
train<-read.csv(file = 'training.csv')
test<-read.csv(file='test.csv')
```

##Data Manipulation
```{r,cache=TRUE}
#first partition the data
library(caret)
set.seed(11)
inTrain<-createDataPartition(train$classe,p=0.8,list=FALSE)
training<-train[inTrain,]
testing<-train[-inTrain,]

# next clean up the 'useless' columns
# remove columns with NAs
training<-training[,colSums(is.na(training))==0]

#remove near zero columns
s1<-nearZeroVar(training)
training<-training[,-s1]

#remove unnecessary columns
s2<- c("X", "user_name", "raw_timestamp_part_1", "raw_timestamp_part_2", "cvtd_timestamp", "new_window", "num_window")
training<-training[,!names(training) %in% s2]
```

##Train the model with cross validation
```{r,cache=TRUE}
# use random forest. Pros for its accuracy while cons are speed, interpretability, #overfitting
library(randomForest)
model<-train(classe~.,data=training,method='rf',prox=TRUE)

#model performance on training set
pred1<-predict(model,training)
print(confusionMatrix(pred1,training$classe))

#performance on cross validation set
pred2<-predict(model,testing)
print(confusionMatrix(pred2,testing$classe))

```

Based on the two outputs, the model is good for both the training set and the cross validation set. Out of sample accuracy is 99.5% and error is just about 0.5%.

##Predict the given test dataset.
```{r}
newP<-predict(model,test) # predict the new test data
# prediction assignment submission

pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}
pml_write_files(newP)


```

